name: configserver

applabels: configserver
#=====================
# DEPLOYMENT
#=====================

image:
  name: configserver-container
  repository: config-server
  tag: "02"
  port: 120
# cmt
resources:
  enabled: false
  # request:
  #   memory: 64Mi
  #   cpu: 250m
  # limit:
  #   memory: 128Mi
  #   cpu: 500m

#======================
# SERVICE
#=====================
service:
  enabled: true

#======================
# INGRESS
#=====================
ingress: 
  enabled: false
  domain: configserver.argocd

#======================
# CONFIGMAP
#=====================

configmap:
  enabled: false
#   data:
#     server.port: "${PORT_SERVICE}"
#     spring.application.name: "${NAME_SERVICE}"

#======================
# ROUTE
#======================
route:
  enabled: true
  hostService: configserver
  defaultHost: apps.ocp-poc.lpc.lab


#======================
# VOLUMES AND MOUNTVOLUMES
#======================

env: 
  enabled: false
  data: {}

#======================
# SECRETS
#======================
secret:
  enabled: true
  portService: 80
  portTarget: 8888
  DB_HOST: 0.tcp.ap.ngrok.io
  DB_USER: sa
  DB_PASS: Root1234
  SPRING_RABBITMQ_USERNAME: default_user_IRR_5BKklxM_f0qmfib 
  SPRING_RABBITMQ_PASSWORD: Xuc4F62yQzJlSzM18bM9fAf873icE-D-
  SPRING_RABBITMQ_HOST: rabbitmq-deploy.rabbitmq.svc.cluster.local
  SPRING_RABBITMQ_PORT: 5672


extraSecrets:
  enabled: false

#======================
# PVC
#======================
pvc: 
  enabled: false
