name: configserver

applabels: configserver
#=====================
# DEPLOYMENT
#=====================

image:
  name: configserver-container
  repository: config-server
  tag: "02"
  port: 120
# cmt
resources:
  enabled: false
  # request:
  #   memory: 64Mi
  #   cpu: 250m
  # limit:
  #   memory: 128Mi
  #   cpu: 500m

#======================
# SERVICE
#=====================
service:
  enabled: true

#======================
# INGRESS
#=====================
ingress:
  enabled: false
  domain: configserver.argocd

#======================
# CONFIGMAP
#=====================

configmap:
  enabled: false
#   data:
#     server.port: "${PORT_SERVICE}"
#     spring.application.name: "${NAME_SERVICE}"

#======================
# ROUTE
#======================
route:
  enabled: true
  hostService: configserver
  defaultHost:


#======================
# VOLUMES AND MOUNTVOLUMES
#======================

env:
  enabled: false
  data: {}

#======================
# SECRETS
#======================
secret:
  enabled: true
  portService: 80
  portTarget: 8888
  DB_HOST: 0.tcp.ap.ngrok.io
  DB_USER: sa
  DB_PASS: Root1234
  SPRING_RABBITMQ_USERNAME:
  SPRING_RABBITMQ_PASSWORD:
  SPRING_RABBITMQ_HOST: .rabbitmq.svc.cluster.local
  SPRING_RABBITMQ_PORT: 5672


extraSecrets:
  enabled: false

#======================
# PVC
#======================
pvc:
  enabled: true
  name: configserver-pvc
  accessMode: ReadWriteMany
  storageClass: nfs-storage
  storage: 3Gi
  storageClassName:
    name: nfs-storage

#----------------------
# VOLUMES AND MOUNTVOLUMES
#----------------------
volumeMounts:
  enabled: true
  name: configserver-pvc
  mountPath: /tmp/

volumes:
  enabled: true
  name: configserver-pvc
  persistentVolumeClaim:
      claimName: configserver-pvc