name: productservice

applabels: productservice
#=====================
# DEPLOYMENT
#=====================

image:
  name: productservice-container
  repository: productservice
  tag: "05"
  port: 120

resources:
  enabled: false
  request:
    memory: 64Mi
    cpu: 250m
  limit:
    memory: 128Mi
    cpu: 500m

#======================
# SERVICE
#=====================
service:
  enabled: true

#======================
# INGRESS
#=====================
ingress: 
  enabled: false
  domain: product.argocd
route:
  enabled: false
#======================
# CONFIGMAP
#=====================

configmap:
  enabled: false
#   nameConfigMap: orderservice-be-application-propertie-configmap
#   data:
#     server.port: "${PORT_SERVICE}"
#     spring.application.name: "${NAME_SERVICE}"


#======================
# VOLUMES AND MOUNTVOLUMES
#======================



#======================
# SECRETS
#======================
secret:
  enabled: true
  portService: 80
  portTarget: 8082

env:
  enabled: true
  0:
    name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: configserver-secret
        key: DB_HOST
        optional: false
  1:
    name: DB_USER
    valueFrom:
      secretKeyRef:
        name: configserver-secret
        key: DB_USER
        optional: false
  2:
    name: DB_PASS
    valueFrom:
      secretKeyRef:
        name: configserver-secret
        key: DB_PASS
        optional: false
  
extraSecrets:
  enabled: false
#======================
# PVC
#======================
pvc:
  enabled: false
